### PR TITLE
Makes specs to be runner with Kahlan.

### PR DESCRIPTION
**Pull request by jails**
Hi, to make my test framwork the more flexible as possible, I'm just poking around different kind of repositories structures and trying to make it works.

So it's not really a request for changing the test framework you are using. (event if it'll give you some great information about code coverage out of the box (see travis log) and also has some cool feature like being able to run only a subset of specs using `ddescribe` `ccontext` `iit` like in Jasmine).

Anyhow for an unknown reason I wasn't able to make specs to pass on travis. Don't know what's going on out there. Also tried to bump capybara-webkit version up to 1.4.1 without luck, still get the same error message

### CODE REVIEW

**Comment by bertrandmoulard** [comment]
Hi Simon
Thanks for trying to make my suite work with Kahlan. I like the ddescribe, ccontext and iit feature. I used to work at Pivotal Labs and spent a lot of time work with/on Jasmine. I'll take a good look at Kahlan when I have some time and might consider replacing Pho.

The travis issue: I spent time on Friday setting it up and though QT and capybara-webkit seem to install ok, it looks like the capybara-webkit browser is having issues visiting the pages served by the test HTTP server. I chatted with someone in the travis IRC chatroom and they just sent me a debug VM today. Hopefully I'll get to the bottom of it soon.

**Comment by jails** [comment]
Cool, please feel free to leave a comment here to keep me posted about this travis issue if you get a chance because this bug leaves me disappointed ;-)

**Comment by bertrandmoulard** [comment]
I fixed the build. A previous pull request had introduced sudo:false in travis yml and I need sudo to install the QT libs.

**Comment by jails** [comment]
Oh awesome ! Thanks for the update !

**Comment by bertrandmoulard** [comment]
Hi Simon

I have a bunch of question I'd like to ask you about Kahlan before I start
pushing for adoption where I work. Could you please email me at
bertrandmoulard at gmail so we can start a private thread about it?

thank you!

**Pull request closed without merging**
